%web_drop_table(WORK.IMPORT); 
 
 
FILENAME REFFILE '/home/u45209732/train.csv'; 
 
PROC IMPORT DATAFILE=REFFILE 
	DBMS=CSV 
	OUT=WORK.IMPORT; 
	GETNAMES=YES; 
RUN; 
 
PROC CONTENTS DATA=WORK.IMPORT; RUN; 
 
 
%web_open_table(WORK.IMPORT);
